# -*- coding: utf-8 -*-
"""Repair the RTL of an existing Hebrew workbook, in place or to a new file.

    python fix_rtl.py broken.xlsx                  # writes broken.rtl.xlsx
    python fix_rtl.py broken.xlsx -o fixed.xlsx
    python fix_rtl.py broken.xlsx --in-place

Why this exists: tools that write Excel have no concept of RTL. The Excel MCP server,
pandas `to_excel`, most export buttons, and anything generated by an agent that has not
read this skill all produce a **left-to-right sheet with Hebrew in it** — the exact defect
this skill is about. Verified: a sheet written through excel-mcp-server comes out with
`rightToLeft` unset, no `readingOrder` on any cell, and no column widths.

This fixes what can be fixed mechanically:

  * `sheet_view.rightToLeft` on every sheet that contains Hebrew
  * `readingOrder=2` on every cell holding text, preserving existing alignment
  * horizontal alignment defaulted to right for text cells that have none
  * estimated column widths, since Hebrew clips at the default width
  * gridlines off on sheets that already carry formatting

It does NOT invent design. Layout, colour, wording and structure still need a human or the
skill's guidance — see reference/design-for-managers.md.
"""
from __future__ import annotations

import argparse
import os
import re

import openpyxl
from openpyxl.styles import Alignment

HEBREW = re.compile(r"[֐-׿]")


def fix(path: str, out: str, widths: bool = True, gridlines: bool = True) -> dict:
    wb = openpyxl.load_workbook(path)
    stats = {"sheets": 0, "sheets_flipped": 0, "cells": 0, "columns": 0}

    for ws in wb.worksheets:
        stats["sheets"] += 1
        cells = [c for row in ws.iter_rows() for c in row if c.value is not None]
        has_hebrew = any(isinstance(c.value, str) and HEBREW.search(c.value) for c in cells)
        if not has_hebrew:
            continue

        if not ws.sheet_view.rightToLeft:
            ws.sheet_view.rightToLeft = True
            stats["sheets_flipped"] += 1

        for c in cells:
            if not isinstance(c.value, str):
                continue
            a = c.alignment
            if a.readingOrder and int(a.readingOrder) == 2:
                continue
            # Preserve whatever alignment the cell already had; only add what is missing.
            c.alignment = Alignment(
                horizontal=a.horizontal or ("right" if not c.value.startswith("=") else None),
                vertical=a.vertical or "center",
                wrap_text=a.wrap_text,
                indent=a.indent,
                shrink_to_fit=a.shrink_to_fit,
                text_rotation=a.text_rotation,
                readingOrder=2,
            )
            stats["cells"] += 1

        if widths:
            # `ws.column_dimensions` is a defaultdict: merely READING
            # `ws.column_dimensions['A'].width` creates the entry and returns the phantom
            # default 13.0 — which then gets serialised as a real <col> record on save.
            # So probing to test "is this sized?" both lies (13.0 is truthy) and silently
            # writes a uniform useless width to every column. `customWidth` is True on the
            # phantom too, so it is no help. Membership is the only honest signal, and it
            # must be tested BEFORE touching the key.
            already_sized = {k for k, d in ws.column_dimensions.items() if d.width}
            for col in ws.columns:
                letter = None
                longest = 0
                for cell in col:
                    if letter is None:
                        letter = cell.column_letter
                    if cell.value is None:
                        continue
                    longest = max(longest, len(str(cell.value)))
                if letter and letter not in already_sized:
                    # 1.3 factor: Hebrew renders wider than the same character count in Latin.
                    ws.column_dimensions[letter].width = max(12, min(50, int(longest * 1.3) + 4))
                    stats["columns"] += 1

        if gridlines and any(c.fill and c.fill.fill_type == "solid" for c in cells):
            ws.sheet_view.showGridLines = False

    wb.save(out)
    return stats


def main() -> int:
    ap = argparse.ArgumentParser(description="Repair RTL in a Hebrew Excel workbook")
    ap.add_argument("path")
    ap.add_argument("-o", "--out", help="output path (default: <name>.rtl.xlsx)")
    ap.add_argument("--in-place", action="store_true", help="overwrite the input file")
    ap.add_argument("--no-widths", action="store_true", help="leave column widths alone")
    args = ap.parse_args()

    if not os.path.exists(args.path):
        print(f"no such file: {args.path}")
        return 1

    if args.in_place:
        out = args.path
    elif args.out:
        out = args.out
    else:
        stem, ext = os.path.splitext(args.path)
        out = f"{stem}.rtl{ext}"

    s = fix(args.path, out, widths=not args.no_widths)
    print(f"  sheets scanned      {s['sheets']}")
    print(f"  sheets flipped RTL  {s['sheets_flipped']}")
    print(f"  cells given RTL     {s['cells']}")
    print(f"  columns sized       {s['columns']}")
    print(f"  written to          {out}")
    print("\n  Now re-check it:  python verify_rtl.py \"%s\" --com" % out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
